Add API endpoint to create thumbnails by candidate
RaitoBezarius/unionGov pull request #17
Opened 2021-12-21 22:25 UTC by yvan-sraka

TODO:

- [ ] cache images generated in `MEDIA_ROOT`
- [ ] create thumbnails for a given government ID
- [ ] write few doc comments

2021-12-21 22:28 UTC, RaitoBezarius requested changes
Quelques petits trucs et on est bon

2021-12-21 22:28 UTC, RaitoBezarius commented on unionGov/gov/views.py
> +    background = square(Image.open(f"unionGov/media/{candidate.image_file}"), size)
faut utiliser `MEDIA_ROOT` cela dit et `candidate.image_url` en général je pense sinon ça va planter dans plein de situations

2021-12-21 22:28 UTC, RaitoBezarius commented on unionGov/gov/views.py
> +    foreground = square(Image.open("gov/templates/statics/thumbnail.png"), size)
récupérer le chemin par un resolveur de Django plutôt que de hardcoder le chemin

2021-12-21 22:28 UTC, RaitoBezarius commented on unionGov/gov/views.py
> +    response = HttpResponse(content_type="image/png")
je pensais le faire côté client ce genre de trucs mais OK

2021-12-21 22:28 UTC, RaitoBezarius commented on unionGov/gov/views.py
> +    response = HttpResponse(content_type="image/png")
(de superposer les deux images)

2021-12-21 22:28 UTC, RaitoBezarius commented on frontend/public/credits.md
> +- [yvan-sraka](https://github.com/yvan-sraka)
je crois qu'il faut que tu te mettes en premier, c'est par ordre de contribution

2021-12-23 08:03 UTC, yvan-sraka commented on unionGov/gov/views.py
> +    background = square(Image.open(f"unionGov/media/{candidate.image_file}"), size)
`candidate.image_url` et pas `candidate.image_file` du coup ?

2021-12-23 08:04 UTC, yvan-sraka commented on unionGov/gov/views.py
> +    foreground = square(Image.open("gov/templates/statics/thumbnail.png"), size)
J'utilise `STATIC_ROOT` :)

2021-12-23 13:54 UTC, RaitoBezarius approved these changes
LGTM

2021-12-23 13:54 UTC, merged